#!/bin/bash
source /etc/environment
source $HOME/.zshrc
source $HOME/.profile
source $HOME/.bashrc
if ! [ -f $HOME/.jupyter/jupyter_server_config.json ]; then
    echo '文件找不到!从备份文件替换密码文件，密码123456'
    mkdir -pv $HOME/.jupyter
    cp -fv $HOME/.jupyter.backup/jupyter_server_config.json $HOME/.jupyter/jupyter_server_config.json
fi
jupyter-lab --allow-root --no-browser --notebook-dir=/notebook --ip=0.0.0.0 --port=8888
