name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Runs every 5 minutes.
  # Runs at 00:00 UTC every day.
  # Actions schedules run at most every 5 minutes.
  schedule:
    # - cron: '*/5 * * * *'
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      id: debian-pyenv
      uses: docker/build-push-action@v3
      with:
        file: build-pyenv
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/debian-pyenv:latest
        platforms: linux/arm64

    - name: Run Docker Image
      run: |
        docker run -v '../install-jupyter/package:/root/export_tar_gz' ${{ secrets.DOCKER_USERNAME }}/debian-pyenv:latest
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: debian-jupyter
      uses: docker/build-push-action@v3
      with:
        file: install-jupyter
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/debian-jupyter:latest
        platforms: linux/arm64
